//! Register structure and API.

use serde::{Deserialize, Serialize};
use std::ops::{Index, IndexMut};
use std::str::FromStr;
use strum::IntoEnumIterator;
use strum_macros::{Display, EnumIter, EnumString};

use super::memory::CAPACITY_BYTES;

/// Collection of general-purpose registers used by the datapath.
#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct GpRegisters {
    pub pc: u64,
    pub gpr: [u64; 32],
}

/// Specifies all of the valid registers accessible in an instance
/// of [`GpRegisters`].
#[derive(Clone, Copy, Debug, Display, EnumIter, EnumString, Eq, PartialEq)]
#[strum(ascii_case_insensitive)]
#[strum(serialize_all = "lowercase")]
pub enum GpRegisterType {
    Pc = -1,
    Zero = 0,
    At = 1,
    V0 = 2,
    V1 = 3,
    A0 = 4,
    A1 = 5,
    A2 = 6,
    A3 = 7,
    T0 = 8,
    T1 = 9,
    T2 = 10,
    T3 = 11,
    T4 = 12,
    T5 = 13,
    T6 = 14,
    T7 = 15,
    S0 = 16,
    S1 = 17,
    S2 = 18,
    S3 = 19,
    S4 = 20,
    S5 = 21,
    S6 = 22,
    S7 = 23,
    T8 = 24,
    T9 = 25,
    K0 = 26,
    K1 = 27,
    Gp = 28,
    Sp = 29,
    Fp = 30,
    Ra = 31,
}

impl GpRegisterType {
    pub fn get_gpr_name(&self) -> String {
        match self {
            GpRegisterType::Pc => self.to_string(),
            _ => format!("{} (r{})", self, *self as u32),
        }
    }
    pub fn is_valid_register_value(&self, value: u64, pc_limit: usize) -> bool {
        match self {
            GpRegisterType::Zero => false, // Zero register is immutable
            GpRegisterType::Pc => {
                // Check if PC is more than the number of instructions or not word-aligned
                value <= pc_limit as u64 && value % 4 == 0
            }
            GpRegisterType::Sp => {
                // Check if SP is more than memory capacity or not word-aligned
                value <= CAPACITY_BYTES as u64 && value % 4 == 0
            }
            _ => true, // Other registers are always considered valid
        }
    }
}

impl ToString for GpRegisters {
    fn to_string(&self) -> String {
        let mut output = String::new();

        output.push_str(&format!("PC = {}\n", self.pc));

        let gpr_registers = self
            .gpr
            .iter()
            .enumerate()
            .map(|(i, inst)| format!("gpr[{i}] = {inst}"))
            .collect::<Vec<String>>()
            .join("\n");
        output.push_str(&gpr_registers);

        output
    }
}

impl Index<&str> for GpRegisters {
    type Output = u64;

    // Convert string to the corresponding RegistersEnum value and use this to index.
    // If this is an invalid string, no enum will be returned, causing a panic as desired.
    fn index(&self, index: &str) -> &Self::Output {
        match GpRegisterType::from_str(index) {
            Ok(register) => &self[register],
            _ => panic!("{index} is not a valid register"),
        }
    }
}

impl IndexMut<&str> for GpRegisters {
    // Convert string to the corresponding RegistersEnum value and use this to index.
    // If this is an invalid string, no enum will be returned, causing a panic as desired.
    fn index_mut(&mut self, index: &str) -> &mut Self::Output {
        match GpRegisterType::from_str(index) {
            Ok(register) => &mut self[register],
            _ => panic!("{index} is not a valid register"),
        }
    }
}

impl Index<GpRegisterType> for GpRegisters {
    type Output = u64;

    fn index(&self, index: GpRegisterType) -> &Self::Output {
        &self.gpr[index as usize]
    }
}

impl IndexMut<GpRegisterType> for GpRegisters {
    fn index_mut(&mut self, index: GpRegisterType) -> &mut Self::Output {
        &mut self.gpr[index as usize]
    }
}

/// Iterator that is used to view each register in the register file.
///
/// This contains a copy of all the registers and their values, and a [`GpRegisterTypeIter`],
/// as generated by [`strum::IntoEnumIterator`]. In other iterator implementations,
/// the internal state might be data like a [`GpRegisterType`]. However, since we can't
/// normally just "add 1" to get to the next register, we use an internal iterator
/// that can track the progression of one [`GpRegisterType`] to the next.
pub struct GpRegistersIter {
    registers: GpRegisters,
    register_iter: GpRegisterTypeIter,
}

/// This implementation of the [`Iterator`] trait essentially wraps the existing
/// [`GpRegisterTypeIter`] so that the register type can be paired with register data.
impl Iterator for GpRegistersIter {
    type Item = (GpRegisterType, u64);

    fn next(&mut self) -> Option<Self::Item> {
        match self.register_iter.next() {
            Some(register_type) => Some((register_type, self.registers[register_type])),
            None => None,
        }
    }
}

/// [`IntoIterator`] is a standard library trait that can convert any type into
/// an [`Iterator`]. In this case, this is an instance of [`GpRegistersIter`] with all the
/// data in the registers and a new [`GpRegisterTypeIter`].
impl IntoIterator for GpRegisters {
    type Item = (GpRegisterType, u64);
    type IntoIter = GpRegistersIter;

    /// Consumes the [`GpRegisters`] struct to create a new [`GpRegistersIter`] that can
    /// be iterated over.
    fn into_iter(self) -> Self::IntoIter {
        GpRegistersIter {
            registers: self,
            register_iter: GpRegisterType::iter(),
        }
    }
}
